/** Static guidance reviewed against packages/shared/src/contracts. Never used for validation. */
export interface FormHelpContent {
  readonly title: string;
  readonly description: string;
  readonly howToFill: string;
  readonly example: string;
  readonly validation: string;
  readonly impact: string;
  readonly warning?: string;
  readonly learnMoreUrl?: `/ajuda${string}`;
}

const noPromise =
  'Use uma fonte oficial e vigente. Simulações não garantem contemplação, rendimento ou aprovação.';
const versioned =
  'Baseie o dado na fonte comercial válida e registre a nova versão da regra quando as condições mudarem.';
const help = (
  title: string,
  description: string,
  howToFill: string,
  example: string,
  validation: string,
  impact: string,
  warning?: string,
): FormHelpContent => ({
  title,
  description,
  howToFill,
  example,
  validation,
  impact,
  ...(warning ? { warning } : {}),
});
const money = (
  title: string,
  description: string,
  impact: string,
  positive = false,
) =>
  help(
    title,
    description,
    'Informe reais, sem R$ nem separador de milhar; use até duas casas decimais.',
    '150000.00',
    positive
      ? 'Informe um valor maior que zero; respeite os limites indicados no campo.'
      : 'Não use valor negativo. Um campo opcional vazio indica dado não informado, não valor zero.',
    impact,
    noPromise,
  );
const percent = (title: string, description: string, impact: string) =>
  help(
    title,
    description,
    'Informe o número do percentual sem o símbolo %. Não converta reais em percentual sem conhecer a base.',
    '2.50 significa 2,5%.',
    'De 0 a 100. Respeite a precisão indicada pelo campo; contratos comerciais aceitam até seis casas decimais.',
    impact,
    `${versioned} ${noPromise}`,
  );
const text = (
  title: string,
  description: string,
  example: string,
  validation: string,
  impact: string,
) =>
  help(
    title,
    description,
    'Use texto claro, fiel ao documento ou ao cadastro de origem.',
    example,
    validation,
    impact,
  );
const choice = (
  title: string,
  description: string,
  example: string,
  impact: string,
) =>
  help(
    title,
    description,
    'Escolha uma das opções exibidas. Use a opção vazia apenas quando o campo permitir.',
    example,
    'Somente as opções disponíveis são aceitas; vínculos e permissões continuam sendo verificados ao salvar.',
    impact,
  );
const date = (
  title: string,
  description: string,
  impact: string,
  validation = 'Use uma data válida; campos opcionais podem ficar vazios.',
) =>
  help(
    title,
    description,
    'Use o calendário ou digite a data no formato exibido pelo navegador.',
    '10/09/2026 (armazenado como 2026-09-10).',
    validation,
    impact,
  );
const toggle = (title: string, description: string, impact: string) =>
  help(
    title,
    description,
    'Marque para ativar esta opção; desmarque para não aplicá-la.',
    'Marcado: opção ativada.',
    'É uma escolha sim/não. As permissões e regras existentes continuam valendo.',
    impact,
  );

export const formHelp = {
  'filter.compare': help(
    'Selecionar para comparar',
    'Escolhe os registros que serão comparados lado a lado.',
    'Marque as opções desejadas e use o botão de comparação.',
    'Selecionar dois grupos da lista.',
    'Respeite o limite de seleção exibido; o contrato aceita até cinco registros.',
    'Altera apenas a seleção da comparação, sem reservar cotas.',
  ),
  'simulation.term': help(
    'Prazo da simulação',
    'Quantidade de meses desejada para o cálculo.',
    'Informe meses inteiros; no novo cenário, vazio mantém o prazo de referência indicado.',
    '120',
    'De 1 a 1200 meses; obrigatório na criação da simulação.',
    'Define o prazo avaliado conforme as regras comerciais, sem prever contemplação.',
  ),
  'administrator.name': text(
    'Nome da administradora',
    'Identifica a instituição responsável pelos grupos e pelas condições comerciais.',
    'Administradora Exemplo',
    'Obrigatório: de 2 a 200 caracteres.',
    'Aparece nos vínculos, listas e consultas comerciais.',
  ),
  'administrator.tradeName': text(
    'Nome fantasia',
    'Nome pelo qual a instituição é conhecida comercialmente.',
    'Exemplo Consórcios',
    'Opcional, até 200 caracteres.',
    'Complementa a identificação; não substitui o nome cadastrado.',
  ),
  'administrator.cnpj': help(
    'CNPJ',
    'Identificação fiscal da administradora.',
    'Copie o CNPJ da fonte oficial, com ou sem pontuação.',
    '11.222.333/0001-81 (exemplo de formato válido).',
    'Opcional; se informado, deve ter 14 dígitos e dígitos verificadores válidos.',
    'Ajuda a identificar a instituição e a verificar duplicidades.',
  ),
  'common.externalCode': text(
    'Código externo',
    'Referência do registro no sistema ou documento de origem.',
    'ADM-001',
    'Opcional, até 100 caracteres nos cadastros operacionais e comerciais.',
    'Facilita conciliação e importação; não substitui o identificador interno.',
  ),
  'common.site': help(
    'Site da instituição',
    'Endereço público oficial para consulta.',
    'Informe a URL completa com http:// ou https://.',
    'https://example.com',
    'URL válida, até 2048 caracteres; somente HTTP ou HTTPS.',
    'Mantém uma referência de consulta no cadastro.',
  ),
  'common.administrator': choice(
    'Administradora vinculada',
    'Instituição responsável pelo produto, grupo ou tabela.',
    'Selecione a administradora cadastrada na lista.',
    'Define a origem do registro e os vínculos comerciais que podem ser usados.',
  ),
  'common.product': choice(
    'Produto vinculado',
    'Produto comercial ao qual o registro pertence.',
    'Imóvel residencial',
    'Relaciona o registro ao catálogo. Confirme a compatibilidade com a administradora.',
  ),
  'common.category': choice(
    'Categoria',
    'Tipo de bem ou serviço atendido.',
    'IMOVEL, AUTOMOVEL, MOTOCICLETA, PESADOS, SERVICOS ou OUTROS, quando disponível.',
    'Classifica o produto e orienta filtros e regras compatíveis nas simulações.',
  ),
  'common.group': choice(
    'Grupo vinculado',
    'Grupo oficial ao qual pertence a participação ou assembleia.',
    'Grupo 00123 da administradora selecionada.',
    'Relaciona cotas, assembleias e histórico ao grupo correto.',
  ),
  'common.description': text(
    'Descrição',
    'Detalhes que ajudam a compreender este cadastro.',
    'Plano para aquisição de imóvel residencial.',
    'Opcional; respeite o limite do campo. Produto e tabela aceitam até 5000 caracteres.',
    'Complementa a consulta do registro; texto livre não cria regras nem altera cálculos.',
  ),
  'common.notes': text(
    'Observações',
    'Contexto adicional relevante para quem consultar o registro.',
    'Condições conferidas na tabela vigente de setembro.',
    'Respeite o limite indicado pelo formulário; evite dados pessoais desnecessários.',
    'Registra contexto; não substitui campos estruturados nem modifica cálculos.',
  ),
  'product.name': text(
    'Nome do produto',
    'Identificação comercial usada no catálogo e nas simulações.',
    'Imóvel residencial',
    'Obrigatório: de 2 a 200 caracteres.',
    'Permite reconhecer o produto nas seleções, grupos e resultados comerciais.',
  ),
  'group.code': text(
    'Código do grupo',
    'Identificador oficial fornecido pela administradora.',
    '00123',
    'Obrigatório: de 1 a 100 caracteres. Preserve zeros à esquerda.',
    'Identifica o grupo em vínculos e no histórico; não use o número de uma cota.',
  ),
  'group.status': choice(
    'Status operacional do grupo',
    'Situação real de funcionamento do grupo.',
    'ATIVO, INATIVO, ENCERRADO, SUSPENSO ou OUTRO.',
    'Atualiza a situação operacional e os filtros; não apaga o histórico.',
  ),
  'group.start': date(
    'Data de início do grupo',
    'Início oficial de funcionamento, quando conhecido.',
    'Permite interpretar o período de operação do grupo.',
  ),
  'group.end': date(
    'Data de encerramento do grupo',
    'Encerramento oficial, quando conhecido.',
    'Registra o período operacional; não invente uma data prevista.',
    'Se início e encerramento forem informados, o encerramento não pode anteceder o início.',
  ),
  'group.term': help(
    'Prazo do grupo',
    'Quantidade de meses prevista no grupo.',
    'Informe meses inteiros, conforme a fonte oficial.',
    '120',
    'Opcional; inteiro de 1 a 1200.',
    'Ajuda a comparar o tempo dos planos; não é uma previsão de contemplação.',
  ),
  'group.quotas': help(
    'Quantidade de cotas',
    'Número de participações previsto para o grupo.',
    'Use um número inteiro, sem separadores.',
    '600',
    'Opcional, de 0 a 10000000.',
    'Descreve o tamanho do grupo; não representa cotas disponíveis para venda.',
  ),
  'group.minCredit': money(
    'Crédito mínimo do grupo',
    'Menor carta de crédito informada para o grupo.',
    'Define o limite inferior da faixa; deve ser menor ou igual ao máximo quando ambos estiverem informados.',
  ),
  'group.maxCredit': money(
    'Crédito máximo do grupo',
    'Maior carta de crédito informada para o grupo.',
    'Define o limite superior da faixa; não pode ser menor que o mínimo informado.',
  ),
  'quota.number': text(
    'Número da cota',
    'Identificador da participação dentro do grupo.',
    '0042',
    'Obrigatório: de 1 a 50 caracteres. Preserve zeros à esquerda.',
    'Distingue a participação das demais cotas do mesmo grupo.',
  ),
  'quota.status': help(
    'Status operacional da cota',
    'Situação operacional registrada para a participação.',
    'Escolha a situação oficial nas opções existentes.',
    'ATIVO, INATIVO, ENCERRADO, SUSPENSO ou OUTRO.',
    'Use apenas os status exibidos. Contemplada e cancelada não são opções deste cadastro.',
    'Atualiza a situação da cota. A contemplação é registrada nos eventos de assembleia, não por este campo.',
  ),
  'quota.credit': money(
    'Valor de crédito da cota',
    'Valor da carta associado à participação, conforme a informação comercial vigente.',
    'Permite consultar o crédito da cota; não é automaticamente o crédito líquido após lances.',
  ),
  'quota.remaining': help(
    'Prazo restante',
    'Quantidade de meses que ainda faltam para esta participação.',
    'Informe o saldo de meses confirmado na fonte.',
    '84',
    'Opcional; inteiro de 0 a 1200.',
    'Permite interpretar o tempo restante; não confunda com o prazo original.',
  ),
  'quota.installment': money(
    'Parcela atual',
    'Valor atual da parcela da cota, conforme a fonte.',
    'Registra o compromisso informado; reajustes futuros não são garantidos por este valor.',
  ),
  'assembly.number': text(
    'Número da assembleia',
    'Referência oficial desta reunião do grupo.',
    '012',
    'Opcional; respeite o identificador da fonte.',
    'Distingue eventos do mesmo grupo.',
  ),
  'assembly.date': help(
    'Data e hora da assembleia',
    'Momento oficial da assembleia.',
    'Use a data e a hora locais no seletor. Confira a fonte antes de registrar resultados.',
    '10/09/2026 14:30',
    'Data e hora válidas; obrigatório neste formulário.',
    'Localiza lances e contemplações no histórico. Para contemplação, registre somente resultado confirmado.',
  ),
  'assembly.status': choice(
    'Status da assembleia',
    'Indica se a reunião está agendada, realizada ou em outra situação disponível.',
    'AGENDADA, quando a reunião ainda vai ocorrer.',
    'Diferencia agenda e resultados efetivos; não transforma previsão em contemplação.',
  ),
  'assembly.quota': choice(
    'Cota do evento',
    'Participação vinculada ao lance ou à contemplação.',
    'Cota 0042; Não identificada quando ainda não há vínculo.',
    'Associa o evento à participação correta dentro do grupo.',
  ),
  'bid.type': choice(
    'Tipo de lance',
    'Modalidade do lance registrado oficialmente.',
    'LIVRE, FIXO, EMBUTIDO ou OUTRO.',
    'Classifica o lance no histórico; não modifica as regras do grupo.',
  ),
  'bid.percent': help(
    'Percentual do lance',
    'Percentual oficial registrado para o lance, na base adotada pela administradora.',
    'Informe o número sem %. Confira a base na fonte oficial.',
    '25.50',
    'Opcional; de 0 a 999.999999, com até seis casas decimais, conforme o contrato de eventos.',
    'Alimenta o histórico de lances; não deduzimos a base apenas pelo percentual.',
    noPromise,
  ),
  'bid.amount': money(
    'Valor do lance',
    'Valor em reais registrado oficialmente para este lance.',
    'Complementa o percentual. Não presuma conversão automática entre os dois campos.',
  ),
  'bid.result': choice(
    'Resultado do lance',
    'Informa se o lance foi efetivamente contemplado.',
    'Não contemplado, enquanto não houver confirmação oficial.',
    'Distingue lances registrados e vencedores nas análises históricas.',
  ),
  'bid.origin': choice(
    'Origem do registro',
    'Como a informação chegou ao sistema.',
    'MANUAL para digitação a partir da fonte conferida.',
    'Preserva a identificação da origem para consulta e auditoria.',
  ),
  'award.type': choice(
    'Tipo de contemplação',
    'Forma oficial pela qual ocorreu a contemplação.',
    'SORTEIO, LANCE ou OUTRO.',
    'Classifica resultados confirmados da assembleia. Não é uma previsão de contemplação.',
  ),
  'table.name': text(
    'Nome da tabela comercial',
    'Identificação legível da tabela de preços e condições.',
    'Imóveis — setembro de 2026',
    'Obrigatório, de 2 a 200 caracteres.',
    'Ajuda a reconhecer a versão comercial utilizada.',
  ),
  'table.code': text(
    'Código da tabela',
    'Referência da tabela na fonte comercial.',
    'IMOVEL-2026-09',
    'Obrigatório, de 1 a 100 caracteres.',
    'Identifica a tabela; mantenha a referência da versão de origem.',
  ),
  'table.start': date(
    'Início da vigência',
    'Data a partir da qual as condições da fonte são válidas.',
    'Distingue condições vigentes de versões antigas.',
    'Obrigatório; não pode ser posterior ao fim da vigência informado.',
  ),
  'table.end': date(
    'Fim da vigência',
    'Último dia de validade informado para a tabela.',
    'Limita a vigência consultada; vazio representa ausência de término informado.',
    'Opcional; não pode anteceder o início da vigência.',
  ),
  'table.status': choice(
    'Status da tabela',
    'Situação comercial da tabela cadastrada.',
    'ATIVA, INATIVA ou ENCERRADA.',
    'Controla sua situação nas consultas. Não apaga versões anteriores.',
  ),
  'table.index': text(
    'Índice de correção',
    'Nome ou referência do índice previsto na fonte comercial.',
    'INCC, apenas se previsto na tabela oficial.',
    'Opcional, até 100 caracteres.',
    'Documenta a correção prevista; este texto não calcula reajustes automaticamente.',
  ),
  'table.participants': help(
    'Participantes',
    'Quantidade de participantes informada na tabela ou no plano.',
    'Informe um número inteiro confirmado pela fonte.',
    '600',
    'Opcional; inteiro de 0 a 10000000.',
    'Contextualiza a oferta; não indica disponibilidade de cotas.',
  ),
  'table.credit': money(
    'Crédito de referência',
    'Valor da carta usado como referência neste plano da tabela vigente.',
    'Identifica o plano comercial junto com prazo e modalidade.',
    true,
  ),
  'table.term': help(
    'Prazo do plano',
    'Quantidade de meses prevista no plano comercial.',
    'Informe o prazo oficial em meses inteiros.',
    '120',
    'Obrigatório; inteiro de 1 a 1200.',
    'Compõe a identificação do plano e a leitura das parcelas.',
  ),
  'table.mode': choice(
    'Modalidade do plano',
    'Modalidade comercial descrita pela fonte.',
    'NORMAL, MAIS_POR_MENOS ou OUTRA.',
    'Diferencia planos da mesma carta e prazo.',
  ),
  'table.planCode': text(
    'Código do plano',
    'Identificador oficial do plano dentro da tabela.',
    'PLANO-120-N',
    'Opcional, até 100 caracteres.',
    'Facilita conferência da oferta com a administradora.',
  ),
  'table.delete': help(
    'Confirmação de exclusão',
    'Confirma a ação indicada nesta janela.',
    'Leia as condições apresentadas e digite exatamente EXCLUIR apenas se desejar continuar.',
    'EXCLUIR',
    'O texto deve coincidir exatamente. A ajuda não confirma nem executa a exclusão.',
    'Habilita a confirmação explícita; o botão de ação continua sendo necessário.',
  ),
  'fees.admin': percent(
    'Taxa de administração',
    'Percentual cobrado pela administração do plano, conforme a fonte.',
    'Compõe as taxas comerciais consideradas quando a regra é usada.',
  ),
  'fees.reserve': percent(
    'Fundo de reserva',
    'Percentual reservado conforme as condições do grupo ou plano.',
    'Compõe o custo informado; não é uma reserva livre do cliente.',
  ),
  'fees.insurance': percent(
    'Seguro',
    'Percentual de seguro previsto na condição comercial.',
    'Pode compor os custos quando o cenário inclui seguro e há regra válida.',
  ),
  'fees.adhesion': percent(
    'Taxa de adesão',
    'Percentual de adesão informado na regra.',
    'Compõe o custo de adesão considerado no cálculo existente.',
  ),
  'fees.total': percent(
    'Taxa total',
    'Percentual total divulgado na tabela oficial.',
    'Preserva o total informado. Não some taxas por conta própria se a fonte já as inclui.',
  ),
  'fees.advancePercent': percent(
    'Taxa antecipada em percentual',
    'Parte antecipada cobrada conforme a tabela.',
    'Complementa as condições de entrada; não confunda percentual com valor em reais.',
  ),
  'fees.advanceAmount': money(
    'Taxa antecipada em reais',
    'Valor antecipado divulgado para o plano.',
    'Registra a condição inicial do plano.',
  ),
  'fees.insuranceAmount': money(
    'Seguro em reais',
    'Valor monetário de seguro informado no item comercial.',
    'Complementa o plano; não é o campo de percentual do seguro.',
  ),
  'installment.first': money(
    'Primeira parcela',
    'Valor da primeira cobrança informado pela fonte.',
    'Permite distinguir a entrada das parcelas seguintes.',
  ),
  'installment.later': money(
    'Demais parcelas',
    'Valor das cobranças seguintes informado pela fonte.',
    'Descreve a continuidade do plano; não garante ausência de reajustes.',
  ),
  'installment.standard': money(
    'Parcela padrão',
    'Parcela de referência do plano comercial.',
    'Permite comparar parcelas conhecidas entre ofertas.',
  ),
  'rule.name': text(
    'Nome da regra',
    'Identificação da condição comercial versionada.',
    'Imóveis — regra setembro de 2026',
    'Obrigatório, de 2 a 200 caracteres.',
    'Identifica a regra aplicada e sua versão nos cálculos.',
  ),
  'rule.start': date(
    'Vigência da regra',
    'Início de validade da condição documentada.',
    'Uma nova regra deve representar uma versão baseada em fonte válida; não reescreva a origem de cálculos anteriores.',
  ),
  'rule.product': choice(
    'Produto da regra',
    'Produto específico atendido; sem produto, a regra é por categoria.',
    'Regra por categoria, quando a fonte não restringe a um produto.',
    'Determina o conjunto de produtos ao qual a regra se aplica.',
  ),
  'rule.embeddedMax': percent(
    'Máximo de lance embutido',
    'Limite de uso do próprio crédito no lance, previsto pela fonte.',
    'Limita o lance embutido permitido na regra; reduz o crédito disponível conforme a base configurada.',
  ),
  'rule.embeddedBasis': choice(
    'Base do lance embutido',
    'Valor sobre o qual o percentual do lance embutido é aplicado.',
    'CONTRACTED_CREDIT (crédito contratado) ou PLAN_TOTAL (total do plano).',
    'Muda a base do cálculo. Escolha somente conforme a fonte oficial e a versão da regra.',
  ),
  'rule.bidType': choice(
    'Tipo de lance próprio',
    'Forma de lance próprio prevista na regra.',
    'FREE (livre), FIXED (fixo) ou PERCENTUAL (limitado).',
    'Orienta o tratamento do lance no cálculo conforme a regra vigente.',
  ),
  'rule.ownMax': percent(
    'Máximo de lance próprio',
    'Limite percentual previsto para recursos próprios.',
    'Limita o lance próprio quando a regra exige esse teto.',
  ),
  'rule.ratio': percent(
    'Proporção crédito/valor da categoria',
    'Relação usada para derivar o crédito a partir do valor do bem ou serviço.',
    'Afeta o crédito contratado no modo Valor da categoria; use a proporção oficial.',
  ),
  'rule.minTerm': help(
    'Prazo mínimo',
    'Menor prazo admitido pela regra ou pelo filtro.',
    'Informe meses inteiros.',
    '60',
    'De 1 a 1200; mantenha coerência com o prazo máximo.',
    'Restringe os planos considerados; não indica prazo de contemplação.',
  ),
  'rule.maxTerm': help(
    'Prazo máximo',
    'Maior prazo admitido pela regra ou pelo filtro.',
    'Informe meses inteiros.',
    '120',
    'De 1 a 1200; mantenha coerência com o prazo mínimo.',
    'Restringe os planos considerados; não indica prazo de contemplação.',
  ),
  'rule.reduced': percent(
    'Parcela reduzida',
    'Percentual de redução definido na condição comercial.',
    'Afeta a parcela reduzida conforme a fórmula já implementada e a versão da regra.',
  ),
  'rule.allowInsurance': toggle(
    'Seguro permitido',
    'Indica se a regra permite considerar seguro.',
    'Controla a elegibilidade do seguro nesta regra; deve refletir a fonte comercial.',
  ),
  'rule.allowEmbedded': toggle(
    'Lance embutido permitido',
    'Indica se a condição comercial permite usar parte do crédito como lance.',
    'Habilita esse tratamento para a regra, sem garantir contemplação.',
  ),
  'rule.allowStructured': toggle(
    'Operação estruturada permitida',
    'Indica se a fonte comercial permite este tipo de operação.',
    'Participa da verificação de compatibilidade com a simulação.',
  ),
  'rule.active': toggle(
    'Regra ativa',
    'Situação de uso da versão cadastrada.',
    'Define se a versão está ativa; preserve a rastreabilidade das condições anteriores.',
  ),
  'rule.reducedUntilAward': toggle(
    'Parcela reduzida até contemplação',
    'Condição que relaciona a redução da parcela à contemplação.',
    'Registra a condição da fonte para o cálculo existente; não prevê quando haverá contemplação.',
  ),
  'rule.dilute': toggle(
    'Diluir desconto após contemplação',
    'Indica a redistribuição prevista para as parcelas reduzidas.',
    'Afeta o tratamento das parcelas posteriores conforme a regra; use apenas a condição oficial.',
  ),
  'rule.inProgress': toggle(
    'Permitir cota em andamento',
    'Indica se a regra admite participação já em curso.',
    'Participa da compatibilidade das cotas avaliadas pela simulação.',
  ),
  'filter.period': choice(
    'Período da consulta',
    'Intervalo de datas dos indicadores exibidos.',
    'Últimos 30 dias, quando disponível.',
    'Muda o intervalo consultado, sem alterar os registros.',
  ),
  'config.organization': text(
    'Nome da organização',
    'Nome institucional mostrado nos documentos comerciais.',
    'Larcarvalho',
    'De 2 a 200 caracteres.',
    'Identifica a organização nas propostas.',
  ),
  'config.rounding': choice(
    'Arredondamento',
    'Critério aplicado aos valores pelo cálculo existente.',
    'HALF_UP: metade para cima; UP: para cima; DOWN: para baixo.',
    'Pode alterar centavos dos resultados. Confira a política comercial antes de salvar.',
  ),
  'config.validity': help(
    'Validade padrão da proposta',
    'Quantidade de dias de validade usada como padrão.',
    'Informe dias inteiros.',
    '7',
    'De 1 a 365 dias.',
    'Define o prazo padrão dos documentos gerados; não garante manutenção de condições externas.',
  ),
  'config.prefix': text(
    'Prefixo da regra',
    'Texto inicial usado na identificação das versões comerciais.',
    'LC',
    'Até 20 caracteres; respeite a validação exibida ao salvar.',
    'Ajuda a reconhecer a versão comercial associada ao cálculo.',
  ),
  'config.disclaimer': text(
    'Aviso obrigatório',
    'Texto institucional de condições e limites da proposta.',
    'Condições sujeitas à confirmação pela administradora.',
    'De 20 a 1000 caracteres; mantenha o aviso exigido pela organização.',
    'É incluído nos documentos comerciais. Não prometa contemplação, rendimento ou aprovação.',
  ),
  'simulation.credit': money(
    'Crédito informado',
    'Valor desejado conforme o modo escolhido: contratado, líquido ou valor da categoria.',
    'No modo contratado é a carta inicial; no líquido é o alvo após os descontos considerados; no valor da categoria a regra deriva o contratado.',
    true,
  ),
  'simulation.creditMode': choice(
    'Modo de crédito',
    'Define o significado do valor digitado.',
    'Crédito contratado: carta inicial. Crédito líquido: valor desejado após descontos considerados. Valor da categoria: valor do bem/serviço.',
    'Muda a entrada interpretada pelo cálculo. Os resultados dependem de dados e regras válidas.',
  ),
  'simulation.ownBid': money(
    'Lance próprio disponível',
    'Recursos do cliente destinados ao lance, separados do crédito da carta.',
    'Compõe o lance com recursos próprios; zero significa ausência de recursos informados.',
  ),
  'simulation.embedded': percent(
    'Lance embutido',
    'Parte do crédito usada como lance, quando a regra permitir.',
    'Afeta o lance e o crédito líquido de acordo com a base e os limites da regra.',
  ),
  'simulation.paid': help(
    'Parcelas já pagas',
    'Quantidade de parcelas quitadas informada para a operação.',
    'Informe somente parcelas efetivamente pagas.',
    '12',
    'Inteiro de 0 a 1200.',
    'Compõe os dados da simulação; não representa saldo em reais.',
  ),
  'simulation.sort': choice(
    'Ordenação do cenário',
    'Critério de apresentação dos resultados que fica salvo no cenário.',
    'Maior aderência ou menor parcela.',
    'Muda a ordem de apresentação; não garante aprovação nem contemplação.',
  ),
  'simulation.name': text(
    'Nome do cenário',
    'Identificação desta comparação de condições.',
    'Prazo de 120 meses com seguro',
    'De 2 a 120 caracteres.',
    'Distingue os cálculos e condições salvos na mesma simulação.',
  ),
  'simulation.structured': toggle(
    'Operação estruturada',
    'Sinaliza a intenção de usar uma operação estruturada.',
    'A compatibilidade depende de uma regra comercial que a permita.',
  ),
  'simulation.insurance': toggle(
    'Incluir seguro',
    'Solicita considerar seguro neste cenário.',
    'O cálculo depende de taxa disponível e regra compatível.',
  ),
  'simulation.includeEmbedded': toggle(
    'Incluir lance embutido',
    'Solicita considerar a parte do crédito destinada ao lance.',
    'O cálculo respeita a permissão, base e limite da regra vigente.',
  ),
  'simulation.pin': toggle(
    'Fixar cenário',
    'Destaca este cenário entre os cálculos salvos.',
    'Facilita retornar à comparação escolhida; não altera os valores calculados.',
  ),
  'simulation.selection': help(
    'Origem comercial da simulação',
    'Conjunto de administradoras, produtos, grupos ou cotas que serão considerados.',
    'Marque os registros que deseja avaliar. Sem seleção, são avaliadas as regras compatíveis.',
    'Selecionar um grupo cadastrado para restringir a análise.',
    'Até 100 identificadores por conjunto; os vínculos e a compatibilidade são verificados.',
    'Restringe as ofertas avaliadas. Favoritar não substitui a seleção nem garante disponibilidade.',
  ),
  'simulation.dataStatus': choice(
    'Status dos dados',
    'Indica se o cálculo está completo, tem dados pendentes ou é incompatível.',
    'Dados pendentes, para investigar informações ausentes.',
    'Filtra resultados; não corrige automaticamente dados nem regras.',
  ),
  'proposal.client': choice(
    'Cliente da proposta',
    'Lead ou cliente cadastrado que receberá a proposta.',
    'Selecione a pessoa correta na lista.',
    'Vincula o documento ao contato. Confira antes de gerar ou compartilhar.',
  ),
  'proposal.title': text(
    'Título da proposta',
    'Identificação do documento que será apresentado ao cliente.',
    'Proposta de consórcio para imóvel',
    'Obrigatório, de 2 a 200 caracteres.',
    'Aparece no documento comercial.',
  ),
  'proposal.objective': text(
    'Resumo do objetivo',
    'Necessidade do cliente que a proposta procura atender.',
    'Avaliar crédito de R$ 150 mil para aquisição de imóvel.',
    'Obrigatório, ao menos 10 caracteres.',
    'Contextualiza o documento; não constitui garantia de resultado.',
  ),
  'proposal.status': choice(
    'Status da proposta',
    'Etapa real do documento comercial.',
    'Enviada, após o envio efetivo ao cliente.',
    'Atualiza o histórico. Aceita indica a proposta, não aprovação de crédito ou contemplação.',
  ),
  'proposal.reason': text(
    'Motivo da mudança',
    'Justificativa para alterar a situação da proposta.',
    'Cliente solicitou revisão do prazo.',
    'Até 500 caracteres.',
    'Registra contexto no histórico do documento.',
  ),
  'proposal.whatsapp': help(
    'WhatsApp do cliente',
    'Número de destino para compartilhar a proposta.',
    'Informe país, DDD e telefone; confira o destinatário.',
    '5585999999999',
    'Use somente os dígitos esperados no campo e um telefone válido.',
    'Define o destinatário do compartilhamento; não altera o contato automaticamente.',
  ),
  'sale.item': choice(
    'Item da proposta que gerou a venda',
    'Qual alternativa aceita pelo cliente originou esta operação.',
    'Selecione o item correspondente ao aceite.',
    'A venda copia os valores do snapshot; a proposta não é alterada.',
  ),
  'sale.origin': choice(
    'Origem da venda',
    'Canal que originou a operação comercial.',
    'CRM, para vendas conduzidas pelo funil interno.',
    'Apenas classificação; não altera valores.',
  ),
  'sale.status': choice(
    'Status da venda',
    'Etapa real da operação comercial.',
    'Avance somente após o fato correspondente.',
    'Atualiza o histórico. Transições inválidas são bloqueadas.',
  ),
  'sale.assign': choice(
    'Responsável pela venda',
    'Vendedor ou gestor que conduz a operação.',
    'Selecione alguém da sua equipe quando possível.',
    'A transferência é auditada com origem e destino.',
  ),
  'sale.cancel': choice(
    'Motivo do cancelamento',
    'Código estruturado do encerramento sem contratação.',
    'Escolha o motivo real; detalhe em observações.',
    'A venda é preservada para auditoria; comissões abertas são canceladas.',
  ),
  'contract.status': choice(
    'Status do contrato',
    'Etapa real do instrumento de contratação.',
    'Ativo somente com venda aprovada ou contratada.',
    'Contrato não cria número fictício nem cota presumida.',
  ),
  'commission.value': money(
    'Valor da comissão',
    'Montante em reais com duas casas decimais.',
    'Registre o valor exato informado pela administradora.',
  ),
  'commission.base': choice(
    'Base de cálculo',
    'Sobre o que o percentual incide: crédito, taxa, parcela, valor fixo ou outra.',
    'Defina explicitamente; nunca é inferida.',
    'Base e regra ficam registradas no snapshot da comissão.',
  ),
  'lead.name': text(
    'Nome do lead ou cliente',
    'Pessoa interessada que será acompanhada no CRM.',
    'Maria de Souza',
    'De 2 a 120 caracteres.',
    'Identifica o contato em carteira, simulações e propostas.',
  ),
  'lead.phone': help(
    'Telefone do contato',
    'Canal de contato informado pela pessoa.',
    'Informe DDD e telefone; inclua o país quando necessário.',
    '5585999999999',
    'Informe telefone ou e-mail. Use DDD brasileiro e número de 8 ou 9 dígitos, com ou sem o prefixo 55. O sistema normaliza o telefone.',
    'Permite contato e verificação de duplicidades. Use dados confirmados.',
  ),
  'lead.email': help(
    'E-mail do contato',
    'Endereço eletrônico informado pela pessoa.',
    'Digite o endereço completo, sem espaços.',
    'maria@example.com',
    'E-mail válido, até 254 caracteres. É necessário telefone ou e-mail.',
    'Permite contato e identificação de duplicidades.',
  ),
  'lead.status': choice(
    'Etapa do lead',
    'Situação real do atendimento no funil comercial.',
    'QUALIFICADO, quando essa etapa estiver disponível e for verdadeira.',
    'Atualiza o funil e o histórico. Perda exige os detalhes previstos pelo formulário.',
  ),
  'lead.loss': choice(
    'Motivo da perda',
    'Razão pela qual o atendimento não avançou.',
    'Escolha o motivo da lista; use OUTRO quando nenhum corresponder.',
    'Registra a causa da perda para acompanhamento comercial.',
  ),
  'lead.lossDetail': text(
    'Descrição de outro motivo',
    'Explicação quando o motivo da perda é Outro.',
    'Cliente adiou o projeto por mudança de cidade.',
    'Até 300 caracteres; preencha quando Outro exigir descrição.',
    'Complementa a análise da perda sem mudar o motivo selecionado.',
  ),
  'lead.nextContact': help(
    'Próximo contato',
    'Data e hora combinadas para retomar o atendimento.',
    'Use o seletor de data e hora local; deixe vazio somente se desejar remover o agendamento.',
    '11/09/2026 09:00',
    'Data e hora válidas, quando informadas.',
    'Organiza o acompanhamento no CRM; não envia mensagens automaticamente.',
  ),
  'lead.interaction': choice(
    'Tipo de interação',
    'Forma de contato ou atividade registrada na timeline.',
    'Escolha a opção correspondente ao atendimento realizado.',
    'Classifica o histórico; não executa uma ligação nem envia mensagem.',
  ),
  'lead.interactionText': text(
    'Descrição da interação',
    'Resumo objetivo do atendimento realizado.',
    'Cliente pediu comparação de prazos de 100 e 120 meses.',
    'Obrigatório, até 2000 caracteres.',
    'Preserva o histórico para continuidade do atendimento.',
  ),
  'lead.owner': choice(
    'Responsável pelo lead',
    'Usuário encarregado de acompanhar o contato.',
    'Selecione um vendedor ativo da lista.',
    'Muda a atribuição da carteira, respeitando as permissões existentes.',
  ),
  'lead.interest': choice(
    'Grupo de interesse',
    'Grupo que o contato deseja acompanhar.',
    'Selecione o grupo solicitado pelo cliente.',
    'Acrescenta um interesse ao CRM; não reserva nem compra uma cota.',
  ),
  'lead.primary': toggle(
    'Interesse principal',
    'Identifica o grupo como prioridade do contato.',
    'Destaca o interesse no atendimento; não altera a disponibilidade comercial.',
  ),
  'integration.name': text(
    'Nome da integração',
    'Identificação da conexão ou origem de dados.',
    'Importação da administradora Exemplo',
    'Obrigatório; respeite o limite do contrato ao salvar.',
    'Permite reconhecer a integração no acompanhamento de execuções.',
  ),
  'integration.connector': choice(
    'Conector',
    'Forma usada para obter dados.',
    'MOCK para cenário demonstrativo, quando disponível.',
    'Define quais configurações adicionais precisam ser preenchidas.',
  ),
  'integration.scenario': choice(
    'Cenário demonstrativo',
    'Resultado simulado do conector de demonstração.',
    'Sucesso parcial.',
    'Testa o tratamento de resultados; não representa uma conexão real com fornecedor.',
  ),
  'integration.count': help(
    'Quantidade de registros demonstrativos',
    'Tamanho da resposta simulada.',
    'Informe um número inteiro.',
    '3',
    'De 0 a 100.',
    'Define o volume do cenário demonstrativo.',
  ),
  'integration.url': help(
    'URL autorizada',
    'Endereço da fonte REST permitida pelo ambiente.',
    'Use a URL aprovada pelo responsável técnico.',
    'https://api.example.com/dados (somente se o host estiver autorizado).',
    'URL válida e host na lista de permissão do ambiente. Não inclua credenciais na URL.',
    'Define a origem consultada pelo conector; a ajuda não libera novos hosts.',
  ),
  'integration.auth': choice(
    'Autenticação do conector',
    'Forma de autenticar a consulta à fonte.',
    'Sem autenticação ou Bearer via referência de segredo.',
    'Define como a credencial já configurada será utilizada.',
  ),
  'integration.secret': help(
    'Referência do segredo',
    'Nome da credencial configurada no ambiente, não seu conteúdo.',
    'Informe apenas a referência fornecida pelo responsável técnico.',
    'FORNECEDOR_API_PROD',
    'Comece com letra maiúscula; use letras maiúsculas, números e _. A referência deve existir quando exigida.',
    'Permite localizar a credencial sem colocá-la no formulário.',
    'Nunca cole senha, token ou chave secreta neste campo.',
  ),
  'integration.importId': help(
    'ID da importação pronta',
    'Identificador de um lote preparado para a integração.',
    'Copie o ID de uma importação pronta e autorizada.',
    '550e8400-e29b-41d4-a716-446655440000 (formato; use um ID existente).',
    'Identificador válido e lote no estado exigido; não digite o nome do arquivo.',
    'Vincula a integração ao lote já revisado.',
  ),
  'import.type': choice(
    'Tipo de dado importado',
    'Cadastro de destino das linhas do arquivo.',
    'Grupos, quando o arquivo contém grupos.',
    'Determina as colunas exigidas e as regras de validação.',
  ),
  'import.file': help(
    'Arquivo de importação',
    'Planilha ou CSV com os registros que serão revisados.',
    'Escolha um arquivo local com cabeçalho e dados da fonte autorizada.',
    'grupos-setembro.xlsx',
    'CSV, XLSX ou XLS; máximo de 20 MB.',
    'Inicia a leitura e revisão do lote; selecionar o arquivo não equivale a confirmar a importação.',
  ),
  'import.sheet': choice(
    'Aba da planilha',
    'Folha que contém os registros a importar.',
    'Grupos.',
    'Define de qual aba serão extraídas as colunas e linhas.',
  ),
  'import.mapping': help(
    'Mapeamento de coluna',
    'Relaciona o campo indicado no rótulo a uma coluna do arquivo.',
    'Selecione a coluna que realmente contém essa informação; revise a amostra.',
    'Campo Código do grupo → coluna GRUPO.',
    'Campos obrigatórios devem ser mapeados; as linhas continuam sujeitas à validação do cadastro.',
    'Um mapeamento incorreto pode associar dados ao campo errado. A revisão de erros permanece necessária.',
  ),
  'import.duplicates': choice(
    'Tratamento de duplicidades',
    'Ação para registros já existentes no banco.',
    'Ignorar existentes para preservar o registro atual.',
    'Atualizar usa a chave confiável prevista na importação e pode alterar os dados existentes após confirmação.',
  ),
  'quality.note': text(
    'Observação da qualidade',
    'Evidência ou justificativa da decisão sobre o problema identificado.',
    'Valor conferido com a tabela oficial de setembro.',
    'Até 2000 caracteres; informe o motivo ao reabrir quando solicitado.',
    'Documenta a revisão; não corrige o cadastro automaticamente.',
  ),
  'quality.action': text(
    'Ação realizada',
    'Resumo do que foi feito para tratar a ocorrência.',
    'Corrigido o código no cadastro de origem.',
    'Até 300 caracteres.',
    'Registra a providência tomada para futuras revisões.',
  ),
  'user.name': text(
    'Nome do usuário',
    'Nome da pessoa que acessa o sistema.',
    'Maria de Souza',
    'De 2 a 200 caracteres.',
    'Identifica autoria, atribuições e ações registradas.',
  ),
  'user.email': help(
    'E-mail do usuário',
    'Endereço usado para identificar a conta.',
    'Informe o e-mail completo da pessoa.',
    'maria@example.com',
    'E-mail válido; até 254 caracteres no cadastro. Campos somente de leitura não podem ser alterados aqui.',
    'Identifica o acesso e o usuário; mudança depende das permissões existentes.',
  ),
  'user.phone': help(
    'Telefone/WhatsApp do usuário',
    'Contato profissional da pessoa.',
    'Informe país, DDD e número quando disponível.',
    '+55 85 99999-9999',
    'Até 30 caracteres. Use números e caracteres de telefone aceitos no campo.',
    'Complementa o cadastro de contato; não envia mensagens.',
  ),
  'user.role': choice(
    'Papel do usuário',
    'Conjunto de permissões padrão da conta.',
    'VENDEDOR para uma conta comercial, se disponível para você.',
    'Muda as permissões padrão. Escolha apenas o necessário; restrições existentes continuam valendo.',
  ),
  'user.team': choice(
    'Equipe',
    'Equipe operacional à qual a pessoa será vinculada.',
    'Equipe Comercial Fortaleza.',
    'Organiza vínculos e o alcance de acesso previsto pelas permissões; não concede permissões por si só.',
  ),
  'user.permission': help(
    'Permissão individual',
    'Exceção à permissão padrão do papel, identificada ao lado.',
    'Escolha Herdar, Permitir ou Negar para a ação indicada.',
    'Negar comparador.read impede essa leitura para o usuário.',
    'Somente permissões delegáveis e controles habilitados podem ser alterados.',
    'Muda o acesso efetivo após salvar. Herdar remove a exceção; não modifica o papel nem as proteções de SUPER_ADMIN.',
  ),
  'user.registration': text(
    'Matrícula comercial',
    'Referência interna do vendedor.',
    'VEN-0042',
    'Opcional, até 80 caracteres.',
    'Ajuda a identificar o vendedor nos registros internos.',
  ),
  'user.hired': date(
    'Data de entrada',
    'Data de início do vínculo comercial do vendedor.',
    'Complementa o perfil; não altera permissões nem equipes.',
  ),
  'user.currentPassword': help(
    'Senha atual',
    'Senha da conta conectada.',
    'Digite sua senha atual, sem compartilhá-la.',
    'Sua senha pessoal atual; não use um exemplo público.',
    'Obrigatória; precisa corresponder à senha vigente.',
    'Confirma a identidade antes da troca de senha.',
  ),
  'user.password': help(
    'Nova senha ou senha inicial',
    'Frase-senha para o acesso da conta.',
    'Crie uma frase-senha exclusiva entre 12 e 128 caracteres.',
    'Uma frase inédita com palavras escolhidas por você; nunca copie uma senha de exemplo.',
    'De 12 a 128 caracteres; preserve os requisitos exibidos.',
    'Cria ou redefine o acesso. Na redefinição administrativa, as sessões do usuário são encerradas.',
    'Não registre senhas em observações, mensagens de ajuda ou capturas de tela.',
  ),
  'user.confirmPassword': help(
    'Confirmar nova senha',
    'Conferência para evitar erro de digitação.',
    'Repita exatamente a nova senha escolhida.',
    'O mesmo conteúdo do campo Nova senha.',
    'Deve coincidir com a nova senha; mantenha os limites do campo.',
    'Evita salvar uma senha diferente da pretendida.',
  ),
  'team.name': text(
    'Nome da equipe',
    'Identificação do grupo de trabalho.',
    'Comercial Fortaleza',
    'Obrigatório, de 2 a 120 caracteres.',
    'Aparece nos vínculos e filtros de equipe.',
  ),
  'team.manager': choice(
    'Gestor da equipe',
    'Pessoa responsável por acompanhar a equipe.',
    'Selecione um gestor ativo da lista.',
    'Define o vínculo de gestão, conforme os papéis e permissões existentes.',
  ),
  'team.status': choice(
    'Status da equipe',
    'Indica se a equipe está ativa ou inativa.',
    'Ativa.',
    'Afeta vínculos e o alcance de equipe previsto no sistema; não apaga usuários.',
  ),
  'appearance.name': text(
    'Nome exibido nas propostas',
    'Nome comercial apresentado nos documentos.',
    'Larcarvalho',
    'De 2 a 200 caracteres.',
    'Personaliza a identificação visual nas propostas.',
  ),
  'appearance.image': help(
    'Imagem autorizada',
    'URL do logotipo ou foto que deseja exibir.',
    'Use o endereço completo de uma imagem autorizada.',
    'https://example.com/logo.png',
    'URL válida; até 2048 caracteres. Não use URLs com segredos.',
    'Personaliza a apresentação; não altera permissões ou regras comerciais.',
  ),
  'appearance.theme': choice(
    'Preferência de tema',
    'Preferência visual da sua conta.',
    'Claro, Escuro ou Sistema.',
    'Salva a preferência pessoal; não redefine as paletas pública e administrativa.',
  ),
  'appearance.density': choice(
    'Densidade da interface',
    'Espaçamento preferido para apresentação da interface.',
    'Confortável ou Compacta.',
    'Salva a preferência de apresentação sem alterar dados.',
  ),
  'appearance.motion': toggle(
    'Reduzir movimento',
    'Preferência por menos animações.',
    'Salva a preferência de acessibilidade da conta.',
  ),
  'appearance.preset': choice(
    'Preset de cores',
    'Paleta pronta para iniciar a personalização.',
    'Larcarvalho, quando disponível na área selecionada.',
    'Altera o rascunho da área selecionada; é necessário salvar para persistir.',
  ),
  'appearance.color': help(
    'Cor do elemento indicado',
    'Cor aplicada ao elemento identificado no rótulo, na área pública ou administrativa selecionada.',
    'Use o seletor visual ou digite # seguido de seis dígitos hexadecimais.',
    '#34806b',
    'Formato #RRGGBB. Verifique o indicador de contraste; a orientação não substitui a validação da cor.',
    'Atualiza o preview. Salvar altera somente o tema da área selecionada, sem mudar o outro tema.',
  ),
  'filter.status': choice(
    'Filtro de status',
    'Situação dos registros que deseja consultar.',
    'Todos para não restringir a situação.',
    'Altera somente a lista exibida; não muda o status dos registros.',
  ),
  'filter.relation': choice(
    'Filtro de vínculo',
    'Restringe a consulta ao vínculo indicado no rótulo.',
    'Selecione uma administradora; Todos remove a restrição.',
    'Filtra os resultados sem alterar os vínculos cadastrados.',
  ),
  'filter.date': date(
    'Data do filtro',
    'Limite de data ou data de vigência para a consulta.',
    'Restringe a consulta; não altera datas dos registros.',
    'Use uma data válida e mantenha o início anterior ou igual ao fim do intervalo.',
  ),
  'filter.sort': choice(
    'Ordenação da consulta',
    'Ordem de apresentação dos registros.',
    'Mais recentes, quando disponível.',
    'Organiza a lista sem alterar os registros.',
  ),
  'filter.origin': choice(
    'Origem dos registros',
    'Fonte ou canal de entrada das informações.',
    'MANUAL, quando disponível.',
    'Restringe a consulta à origem escolhida.',
  ),
  'filter.quality': choice(
    'Classificação da qualidade',
    'Severidade, entidade ou situação da ocorrência indicada no rótulo.',
    'Selecione uma classificação exibida na lista.',
    'Ajuda a investigar problemas; não corrige dados automaticamente.',
  ),
  'filter.archive': choice(
    'Exibição de tabelas',
    'Define se a consulta inclui tabelas arquivadas.',
    'Ativas, Arquivadas ou Todas.',
    'Muda apenas a consulta; não arquiva nem restaura tabelas.',
  ),
  'filter.nextContact': choice(
    'Filtro de próximo contato',
    'Recorte da agenda de acompanhamento do CRM.',
    'Escolha uma faixa disponível na lista.',
    'Ajuda a priorizar retornos; não agenda contatos automaticamente.',
  ),
  'filter.onlyMine': toggle(
    'Somente minha carteira',
    'Restringe a lista aos contatos sob sua responsabilidade.',
    'Altera o filtro, preservando as permissões existentes.',
  ),
  'filter.unassigned': toggle(
    'Somente não atribuídos',
    'Mostra contatos que ainda não têm responsável.',
    'Filtra a carteira; não atribui contatos automaticamente.',
  ),
  'filter.inactive': toggle(
    'Incluir registros inativos',
    'Inclui administradoras e produtos inativos na consulta.',
    'Amplia a consulta; não reativa os cadastros.',
  ),
  'filter.available': toggle(
    'Restrição de disponibilidade',
    'Aplica a condição indicada ao conjunto consultado.',
    'Restringe a consulta; não torna um plano ou grupo elegível automaticamente.',
  ),
  'filter.credit': money(
    'Crédito desejado no comparador',
    'Valor que deseja usar como referência na comparação.',
    'Ajuda a selecionar grupos compatíveis com a faixa de crédito.',
  ),
  'filter.installment': money(
    'Parcela máxima',
    'Limite mensal informado para a consulta.',
    'Restringe a comparação às parcelas conhecidas; dado ausente não é promessa de parcela.',
  ),
  'filter.bid': percent(
    'Lance disponível para comparação',
    'Percentual de referência informado para a análise.',
    'Contextualiza a comparação; não representa probabilidade garantida de contemplação.',
  ),
  'knowledge.title': text(
    'Título do documento',
    'Identificação do conteúdo que ficará disponível na base de conhecimento.',
    'Regulamento de consórcio de imóveis — setembro de 2026',
    'Obrigatório, de 2 a 300 caracteres.',
    'Ajuda a localizar o documento nas consultas e nas respostas da IA.',
  ),
  'knowledge.description': text(
    'Descrição do documento',
    'Contexto opcional para orientar quem consulta a base.',
    'Regras de contemplação e prazos vigentes para imóveis.',
    'Opcional, até 2000 caracteres.',
    'Complementa a consulta; não altera a extração do conteúdo nem os cálculos.',
  ),
  'knowledge.category': choice(
    'Categoria do documento',
    'Classificação do tipo de conteúdo armazenado.',
    'MANUAL, REGULAMENTO, TABELA, PROCEDIMENTO, PRODUTO, COMERCIAL, INSTITUCIONAL ou OUTRO.',
    'Organiza filtros e buscas na base de conhecimento.',
  ),
  'knowledge.visibility': choice(
    'Visibilidade do documento',
    'Público fica disponível para toda a organização; Equipe restringe à sua equipe; Privado fica restrito ao autor.',
    'Público para materiais institucionais revisados.',
    'Define quem pode ler o documento. A permissão de leitura continua sendo verificada no backend.',
  ),
  'knowledge.team': choice(
    'Equipe do documento',
    'Equipe autorizada quando a visibilidade é Equipe.',
    'Selecione a equipe responsável pelo material.',
    'Restringe a leitura aos membros da equipe, sem conceder permissões adicionais.',
  ),
  'knowledge.tags': text(
    'Etiquetas do documento',
    'Palavras-chave separadas por vírgula para facilitar a busca.',
    'imóvel, contemplação, prazo',
    'Opcional; até 20 etiquetas de 60 caracteres cada. Repetidas são normalizadas.',
    'Ajuda a filtrar e recuperar documentos na base de conhecimento.',
  ),
  'knowledge.content': text(
    'Conteúdo em texto',
    'Texto integral que será dividido em trechos e indexado para busca e respostas da IA.',
    'Cole aqui o conteúdo revisado do documento, com pelo menos 20 caracteres.',
    'Obrigatório, de 20 a 200000 caracteres. O texto é tratado como dado não confiável.',
    'Alimenta a busca lexical e as respostas fundamentadas. A IA não altera dados financeiros.',
  ),
  'knowledge.file': help(
    'Arquivo do documento',
    'TXT, Markdown ou PDF com texto selecionável até o limite configurado.',
    'Escolha um arquivo local revisado. PDFs digitalizados (imagem) exigem OCR e são recusados.',
    'regulamento-setembro.pdf',
    'Formato permitido, conteúdo correspondente à extensão e dentro do limite de tamanho.',
    'O arquivo é extraído, dividido em trechos e indexado. Documentos duplicados são recusados.',
  ),
  'knowledge.search': help(
    'Busca na base de conhecimento',
    'Consulta lexical pelos documentos autorizados, priorizando os termos informados.',
    'Escreva palavras-chave ou uma pergunta curta sobre o conteúdo desejado.',
    'Como funciona o prazo de contemplação?',
    'Use ao menos 2 caracteres; a busca respeita as permissões e a visibilidade.',
    'Mostra trechos com a pontuação de relevância. Não há busca semântica nesta fase.',
  ),
  'filter.knowledgeStatus': choice(
    'Status do documento',
    'Situação de processamento do documento na base.',
    'READY após o processamento; PROCESSING enquanto extrai e divide o conteúdo.',
    'Filtra a lista exibida; não reprocessa nem reindexa o documento.',
  ),
  'filter.knowledgeCategory': choice(
    'Filtro por categoria',
    'Restringe a consulta às categorias disponíveis de conhecimento.',
    'Selecione uma categoria; Todas remove a restrição.',
    'Filtra a lista sem alterar a classificação dos documentos.',
  ),
  'filter.knowledgeVisibility': choice(
    'Filtro por visibilidade',
    'Restringe a consulta conforme a visibilidade dos documentos.',
    'Público, Equipe ou Privado.',
    'Filtra a lista; as permissões de leitura continuam sendo verificadas.',
  ),
} satisfies Record<string, FormHelpContent>;

export type FormHelpKey = keyof typeof formHelp;

export const tableItemHelpKeys = {
  seguro: 'fees.insuranceAmount',
  taxaAntecipadaValor: 'fees.advanceAmount',
  primeiraParcela: 'installment.first',
  demaisParcelas: 'installment.later',
  parcelaPadrao: 'installment.standard',
  taxaAntecipadaPercentual: 'fees.advancePercent',
  fundoReservaPercentual: 'fees.reserve',
  taxaAdministracaoPercentual: 'fees.admin',
  taxaTotalPercentual: 'fees.total',
  seguroVidaPercentual: 'fees.insurance',
} as const satisfies Record<string, FormHelpKey>;

/** Only the existing internal help page and simple anchors are linkable. */
export function safeHelpUrl(value: string | undefined): string | undefined {
  return value && /^\/ajuda(?:#[a-zA-Z0-9_-]+)?$/.test(value)
    ? value
    : undefined;
}
