import {
  permissions,
  type Permission,
  type UserRole,
} from '@larcarvalho/shared';
import type { AuthContext } from './auth-context.js';

const rolePermissions: Readonly<Record<UserRole, ReadonlySet<Permission>>> = {
  ADMIN: new Set([
    'dashboard.read', 'teams.read', 'teams.read_all', 'teams.create', 'teams.update', 'teams.assign',
    'users.permissions.manage', 'users.reset_password', 'themes.public.manage', 'themes.admin.manage',
    'analytics.read',
    'simulations.read_all',
    'simulations.create',
    'simulations.update_all',
    'simulations.delete_all',
    'proposals.read_all',
    'proposals.create',
    'proposals.update_all',
    'proposals.export',
    'commercial_config.read',
    'commercial_config.update',
    'commercial_rules.read',
    'commercial_rules.manage',
    'integrations.read',
    'integrations.create',
    'integrations.update',
    'integrations.execute',
    'integrations.logs',
    'integrations.test_connection',
    'integrations.pause',
    'integrations.credentials',
    'leads.read_all',
    'leads.create',
    'leads.update_all',
    'leads.assign',
    'leads.change_status',
    'leads.add_interaction',
    'indice_aderencia.read',
    'comparador.read',
    'historico_grupos.read',
    'historico_grupos.create',
    'data_quality.read',
    'data_quality.review',
    'data_quality.resolve',
    'data_quality.scan',
    'importacoes.read',
    'importacoes.create',
    'importacoes.execute',
    'tabelas_comerciais.read',
    'tabelas_comerciais.create',
    'tabelas_comerciais.update',
    'tabelas_comerciais.import',
    'tabelas_comerciais.delete',
    'assembleias.read',
    'assembleias.create',
    'assembleias.update',
    'lances.read',
    'lances.create',
    'lances.update',
    'contemplacoes.read',
    'contemplacoes.create',
    'contemplacoes.update',
    'produtos.read',
    'produtos.create',
    'produtos.update',
    'produtos.deactivate',
    'grupos.read',
    'grupos.create',
    'grupos.update',
    'grupos.deactivate',
    'cotas.read',
    'cotas.create',
    'cotas.update',
    'cotas.deactivate',
    'administradoras.read',
    'administradoras.create',
    'administradoras.update',
    'administradoras.deactivate',
    'users.read',
    'users.create',
    'users.update',
    'users.changeRole',
    'users.deactivate',
    'ai.use',
    'ai.lead_analysis',
    'ai.simulation_explain',
    'ai.comparison_analysis',
    'ai.draft_messages',
    'ai.manager_summary',
    'ai.sales_summary',
    'ai.settings',
    'ai.usage',
    'sales.read_all',
    'sales.create',
    'sales.update_all',
    'sales.change_status',
    'sales.assign',
    'sales.cancel',
    'contracts.read',
    'contracts.create',
    'contracts.update',
    'commissions.read',
    'commissions.create',
    'commissions.confirm',
    'commissions.receive',
    'commissions.reverse',
    'commission_rules.read',
    'commission_rules.manage',
    'knowledge.read',
    'knowledge.search',
    'knowledge.create',
    'knowledge.update',
    'knowledge.process',
    'knowledge.archive',
    'knowledge.manage',
  ]),
  GESTOR: new Set([
    'dashboard.read', 'teams.read',
    'simulations.read_team',
    'simulations.create',
    'simulations.update_team',
    'proposals.read_team',
    'proposals.create',
    'proposals.update_team',
    'proposals.export',
    'commercial_config.read',
    'commercial_rules.read',
    'integrations.read',
    'integrations.execute',
    'integrations.logs',
    'integrations.test_connection',
    'leads.read_team',
    'leads.create',
    'leads.update_team',
    'leads.assign',
    'leads.change_status',
    'leads.add_interaction',
    'indice_aderencia.read',
    'comparador.read',
    'historico_grupos.read',
    'historico_grupos.create',
    'data_quality.read',
    'data_quality.review',
    'data_quality.resolve',
    'data_quality.scan',
    'importacoes.read',
    'importacoes.create',
    'importacoes.execute',
    'tabelas_comerciais.read',
    'tabelas_comerciais.create',
    'tabelas_comerciais.update',
    'tabelas_comerciais.import',
    'assembleias.read',
    'assembleias.create',
    'assembleias.update',
    'lances.read',
    'lances.create',
    'lances.update',
    'contemplacoes.read',
    'contemplacoes.create',
    'contemplacoes.update',
    'administradoras.read',
    'produtos.read',
    'produtos.create',
    'produtos.update',
    'grupos.read',
    'grupos.create',
    'grupos.update',
    'cotas.read',
    'cotas.create',
    'cotas.update',
    'ai.use',
    'ai.lead_analysis',
    'ai.simulation_explain',
    'ai.comparison_analysis',
    'ai.draft_messages',
    'ai.manager_summary',
    'ai.sales_summary',
    'sales.read_team',
    'sales.create',
    'sales.update_team',
    'sales.change_status',
    'sales.assign',
    'sales.cancel',
    'contracts.read',
    'contracts.create',
    'contracts.update',
    'commissions.read',
    'commissions.create',
    'commissions.confirm',
    'commission_rules.read',
    'knowledge.read',
    'knowledge.search',
    'knowledge.create',
    'knowledge.update',
    'knowledge.process',
    'knowledge.archive',
  ]),
  OPERADOR: new Set([
    'dashboard.read',
    'simulations.read_own',
    'proposals.read_own',
    'commercial_config.read',
    'commercial_rules.read',
    'integrations.read',
    'integrations.execute',
    'integrations.logs',
    'indice_aderencia.read',
    'comparador.read',
    'historico_grupos.read',
    'data_quality.read',
    'data_quality.review',
    'importacoes.read',
    'importacoes.create',
    'importacoes.execute',
    'tabelas_comerciais.read',
    'tabelas_comerciais.import',
    'assembleias.read',
    'lances.read',
    'contemplacoes.read',
    'administradoras.read',
    'produtos.read',
    'grupos.read',
    'cotas.read',
    'ai.use',
    'knowledge.read',
    'knowledge.search',
  ]),
  SUPER_ADMIN: new Set(permissions),
  VENDEDOR: new Set([
    'dashboard.read',
    'leads.read_own',
    'simulations.read_own',
    'simulations.create',
    'simulations.update_own',
    'simulations.delete_own',
    'proposals.read_own',
    'proposals.create',
    'proposals.update_own',
    'proposals.export',
    'commercial_rules.read',
    'leads.create',
    'leads.update_own',
    'leads.change_status',
    'leads.add_interaction',
    'indice_aderencia.read',
    'comparador.read',
    'ai.use',
    'ai.lead_analysis',
    'ai.simulation_explain',
    'ai.comparison_analysis',
    'ai.draft_messages',
    'ai.sales_summary',
    'sales.read_own',
    'sales.create',
    'sales.update_own',
    'sales.change_status',
    'sales.cancel',
    'contracts.read',
    'contracts.create',
    'contracts.update',
    'commissions.read',
    'commissions.create',
    'knowledge.read',
    'knowledge.search',
  ]),
};

const rolesManageableByAdmin: ReadonlySet<UserRole> = new Set([
  'GESTOR',
  'VENDEDOR',
  'OPERADOR',
]);

export function hasPermission(actor: UserRole | AuthContext, permission: Permission): boolean {
  const role = typeof actor === 'string' ? actor : actor.user.role;
  if (role === 'SUPER_ADMIN') return true;
  if (typeof actor !== 'string') {
    const overrides = actor.permissionOverrides ?? [];
    if (overrides.some((item) => item.permission === permission && item.effect === 'DENY')) return false;
    if (overrides.some((item) => item.permission === permission && item.effect === 'ALLOW')) return true;
  }
  return rolePermissions[role].has(permission);
}

export function permissionsForActor(actor: AuthContext): readonly Permission[] {
  return permissions.filter((permission) => hasPermission(actor, permission));
}

// Administrators cannot delegate security administration or critical technical access.
const protectedPermissions: ReadonlySet<Permission> = new Set([
  'users.permissions.manage', 'users.reset_password', 'users.changeRole', 'users.create', 'users.update', 'users.deactivate',
  'teams.create', 'teams.update', 'teams.assign', 'commercial_config.update',
  'themes.public.manage', 'themes.admin.manage', 'audit.read',
  'integrations.create', 'integrations.update', 'integrations.test_connection',
  'integrations.credentials',
  'ai.settings',
]);
export function canDelegate(actor: AuthContext, permission: Permission): boolean {
  return actor.user.role === 'SUPER_ADMIN' || (actor.user.role === 'ADMIN' && !protectedPermissions.has(permission) && hasPermission(actor, permission));
}

export function permissionsForRole(role: UserRole): readonly Permission[] {
  return permissions.filter((permission) => hasPermission(role, permission));
}

export function canAssignRole(
  actorRole: UserRole,
  targetRole: UserRole,
): boolean {
  return (
    actorRole === 'SUPER_ADMIN' ||
    (actorRole === 'ADMIN' && rolesManageableByAdmin.has(targetRole))
  );
}

export function canManageUserRole(
  actorRole: UserRole,
  currentTargetRole: UserRole,
): boolean {
  return (
    actorRole === 'SUPER_ADMIN' ||
    (actorRole === 'ADMIN' && rolesManageableByAdmin.has(currentTargetRole))
  );
}
