import { randomUUID } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { createUserRequestSchema, leadListQuerySchema, simulationListQuerySchema, proposalListQuerySchema, dashboardQuerySchema } from '@larcarvalho/shared';
import '../../src/config/load-env.js';
import { parseEnvironment } from '../../src/config/env.js';
import { createPrismaClient } from '../../src/infrastructure/database/prisma-client.js';
import type { Prisma, PrismaClient } from '../../src/generated/prisma/client.js';
import type { AuthContext } from '../../src/core/auth/auth-context.js';
import { IdentityService } from '../../src/modules/identity/identity.service.js';
import { LeadsService } from '../../src/modules/leads/leads.service.js';
import { SimulationsService } from '../../src/modules/simulations/simulations.service.js';
import { ProposalsService } from '../../src/modules/proposals/proposals.service.js';
import { CommercialConfigurationsService } from '../../src/modules/commercial-configurations/commercial-configurations.service.js';
import { DashboardService } from '../../src/modules/dashboard/dashboard.service.js';
import { DashboardRepository } from '../../src/modules/dashboard/dashboard.repository.js';
import { permissionsForActor } from '../../src/core/auth/rbac.js';

const url = process.env.TEST_DATABASE_URL;
describe.skipIf(!url)('real PostgreSQL access management, rolled back', () => {
  it('persists users, seller data, teams and overrides; isolates lists, ids and aggregates; refreshes sessions and audits', async () => {
    const target = new URL(url!);
    if (!['localhost', '127.0.0.1'].includes(target.hostname) || target.pathname !== '/larcarvalho_test') throw new Error('Isolated test database required');
    const config = parseEnvironment({ ...process.env, DATABASE_URL: url, NODE_ENV: 'test', LOG_LEVEL: 'silent' });
    const db = createPrismaClient(config); const rollback = new Error('rollback access fixtures');
    const suffix = randomUUID();
    try {
      await db.$transaction(async (tx) => {
        const scoped = new Proxy(tx, { get: (value, property) => property === '$transaction' ? (operation: ((client: Prisma.TransactionClient) => Promise<unknown>) | Promise<unknown>[]) => typeof operation === 'function' ? operation(tx) : Promise.all(operation) : Reflect.get(value, property) }) as unknown as PrismaClient;
        const identity = new IdentityService(scoped, config); const leads = new LeadsService(scoped); const simulations = new SimulationsService(scoped);
        const proposals = new ProposalsService(scoped, simulations, new CommercialConfigurationsService(scoped));
        const root = await tx.user.create({ data: { nome: 'Root fixture', email: `root-${suffix}@example.test`, role: 'SUPER_ADMIN', passwordHash: 'unused' } });
        const superActor: AuthContext = { sessionId: suffix, user: { id: root.id, nome: root.nome, email: root.email, role: 'SUPER_ADMIN' } };
        const create = (name: string, role: 'ADMIN' | 'GESTOR' | 'VENDEDOR') => identity.createUser(superActor, createUserRequestSchema.parse({ nome: name, email: `${name}-${suffix}@example.test`, password: `Password-${suffix}`, role }), {});
        const manager = await create('manager', 'GESTOR'); const otherManager = await create('othermanager', 'GESTOR'); const seller = await create('maria', 'VENDEDOR'); const other = await create('other', 'VENDEDOR'); const admin = await create('admin', 'ADMIN');
        const adminActor: AuthContext = { sessionId: suffix, user: admin };
        const team = await identity.saveTeam(superActor, null, { name: `Team ${suffix}`, managerId: manager.id }, {});
        const otherTeam = await identity.saveTeam(superActor, null, { name: `Other ${suffix}`, managerId: otherManager.id }, {});
        await identity.assignTeamMember(superActor, seller.id, team.id, {}); await identity.assignTeamMember(superActor, other.id, otherTeam.id, {});
        await identity.updateUser(superActor, seller.id, { telefoneWhatsapp: '85999999999', sellerProfile: { registration: 'M-10', hiredAt: '2026-09-01' } }, {});
        expect((await identity.getUser(superActor, seller.id)).sellerProfile?.registration).toBe('M-10');
        const login = await identity.login(seller.email, `Password-${suffix}`, {}); const managerLogin = await identity.login(manager.email, `Password-${suffix}`, {});
        const sellerActor = (await identity.authenticate(login.token))!; const managerActor = (await identity.authenticate(managerLogin.token))!;
        expect(sellerActor.teamIds).toEqual([team.id]); expect(managerActor.teamIds).toEqual([team.id]);
        const ownLead = await tx.lead.create({ data: { nome: 'Own lead', origem: 'CADASTRO_MANUAL', responsavelId: seller.id, emailNormalizado: `lead-${suffix}@example.test` } });
        const foreignLead = await tx.lead.create({ data: { nome: 'Foreign lead', emailNormalizado: `foreign-${suffix}@example.test`, origem: 'CADASTRO_MANUAL', responsavelId: other.id } });
        const query = leadListQuerySchema.parse({});
        expect((await leads.list(sellerActor, query)).items.map((lead) => lead.id)).toEqual([ownLead.id]);
        expect((await leads.list(sellerActor, { ...query, responsavelId: other.id })).items).toEqual([]);
        expect((await leads.list(sellerActor, { ...query, semResponsavel: true })).items).toEqual([]);
        expect((await leads.list(managerActor, query)).items.map((lead) => lead.id)).toEqual([ownLead.id]);
        await expect(leads.get(managerActor, foreignLead.id)).rejects.toMatchObject({ statusCode: 404 });
        await expect(leads.assign(managerActor, ownLead.id, { responsavelId: other.id })).rejects.toMatchObject({ statusCode: 409 });
        const deniedUpdate: AuthContext = { ...sellerActor, permissionOverrides: [{ permission: 'leads.read_all', effect: 'ALLOW' }] };
        await expect(leads.update(deniedUpdate, foreignLead.id, { nome: 'Should not change' })).rejects.toMatchObject({ statusCode: 404 });
        const ownSimulation = await tx.simulation.create({ data: { number: `SIM-${suffix.slice(0,8)}`, createdById: seller.id, leadId: ownLead.id, category: 'IMOVEL', creditMode: 'CONTRACTED_CREDIT', desiredTermMonths: 120, requestedCredit: 100000 } });
        const foreignSimulation = await tx.simulation.create({ data: { number: `SIM-OTHER-${suffix.slice(0,8)}`, createdById: other.id, leadId: foreignLead.id, category: 'IMOVEL', creditMode: 'CONTRACTED_CREDIT', desiredTermMonths: 120, requestedCredit: 100000 } });
        expect((await simulations.list(managerActor, simulationListQuerySchema.parse({}))).items.map((item) => item.id)).toEqual([ownSimulation.id]);
        await expect(simulations.get(sellerActor, foreignSimulation.id)).rejects.toMatchObject({ statusCode: 404 });
        const ownProposal = await tx.proposal.create({ data: { number: `PROP-${suffix.slice(0,8)}`, createdById: seller.id, leadId: ownLead.id, simulationId: ownSimulation.id, title: 'Own proposal', objectiveSummary: 'Fixture', snapshot: {}, validUntil: new Date('2027-01-01') } });
        const foreignProposal = await tx.proposal.create({ data: { number: `PROP-OTHER-${suffix.slice(0,8)}`, createdById: other.id, leadId: foreignLead.id, simulationId: foreignSimulation.id, title: 'Other proposal', objectiveSummary: 'Fixture', snapshot: {}, validUntil: new Date('2027-01-01') } });
        expect((await proposals.list(managerActor, proposalListQuerySchema.parse({}))).items.map((item) => item.id)).toEqual([ownProposal.id]);
        await expect(proposals.get(managerActor, foreignProposal.id)).rejects.toMatchObject({ statusCode: 404 });
        const dashboard = await new DashboardService(new DashboardRepository(scoped)).overview(managerActor, dashboardQuerySchema.parse({}));
        expect(dashboard.crm?.scope).toBe('TEAM'); expect(dashboard.crm?.activeNow).toBe(1); expect(dashboard.crm?.team.map((item) => item.responsibleId)).toEqual([seller.id]);
        await identity.setUserPermissions(superActor, seller.id, [{ permission: 'comparador.read', effect: 'DENY' }, { permission: 'leads.read_all', effect: 'ALLOW' }], {});
        const refreshed = (await identity.authenticate(login.token))!;
        expect(permissionsForActor(refreshed)).not.toContain('comparador.read'); expect((await leads.list(refreshed, query)).items.some((lead) => lead.id === foreignLead.id)).toBe(true);
        await expect(identity.setUserPermissions(adminActor, seller.id, [{ permission: 'users.permissions.manage', effect: 'ALLOW' }], {})).rejects.toMatchObject({ statusCode: 403 });
        await expect(identity.setUserPermissions(adminActor, admin.id, [], {})).rejects.toMatchObject({ statusCode: 403 });
        await expect(identity.changeUserRole(adminActor, seller.id, 'SUPER_ADMIN', {})).rejects.toMatchObject({ statusCode: 403 });
        await identity.setUserPermissions(superActor, seller.id, [{ permission: 'leads.read_own', effect: 'DENY' }, { permission: 'simulations.read_own', effect: 'DENY' }], {});
        const denied = (await identity.authenticate(login.token))!;
        await expect(leads.get(denied, ownLead.id)).rejects.toMatchObject({ statusCode: 403 });
        await expect(simulations.get(denied, ownSimulation.id)).rejects.toMatchObject({ statusCode: 403 });
        await identity.setUserPermissions(superActor, seller.id, [], {});
        await identity.saveTeam(superActor, team.id, { active: false }, {});
        expect((await identity.authenticate(managerLogin.token))!.teamIds ?? []).toEqual([]);
        expect((await leads.list((await identity.authenticate(managerLogin.token))!, query)).items).toEqual([]);
        await identity.resetUserPassword(superActor, seller.id, `New-password-${suffix}`, {}); expect(await identity.authenticate(login.token)).toBeNull();
        const relogin = await identity.login(seller.email, `New-password-${suffix}`, {});
        await identity.setUserStatus(superActor, seller.id, false, {}); expect(await identity.authenticate(relogin.token)).toBeNull();
        await expect(identity.login(seller.email, `New-password-${suffix}`, {})).rejects.toMatchObject({ statusCode: 401 });
        const actions = (await tx.auditLog.findMany({ where: { actorId: root.id }, select: { action: true } })).map((entry) => entry.action);
        expect(actions).toEqual(expect.arrayContaining(['USER_CREATED', 'TEAM_CREATED', 'USER_TEAM_CHANGED', 'USER_UPDATED', 'USER_PERMISSIONS_CHANGED', 'TEAM_UPDATED', 'USER_PASSWORD_RESET', 'USER_DEACTIVATED']));
        throw rollback;
      }, { timeout: 60000, maxWait: 15000 }).catch((error: unknown) => { if (error !== rollback) throw error; });
    } finally { await db.$disconnect(); }
  }, 90000);
});
