import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';

export interface SaveKnowledgeFileInput {
  readonly buffer: Buffer;
  readonly key: string;
}

export interface KnowledgeStorage {
  readonly kind: 'local' | 'memory';
  read(key: string): Promise<Buffer>;
  remove(key: string): Promise<void>;
  save(input: SaveKnowledgeFileInput): Promise<void>;
}

/**
 * Local filesystem storage for the raw uploaded document. The key is always
 * generated by the service (uuid-based), never derived from user input, so the
 * resolved path cannot escape the base directory.
 */
export class LocalKnowledgeStorage implements KnowledgeStorage {
  readonly kind = 'local' as const;
  private readonly baseDir: string;

  constructor(baseDir: string) {
    this.baseDir = resolve(baseDir);
  }

  private resolveKey(key: string): string {
    const target = resolve(join(this.baseDir, key));
    if (target !== this.baseDir && !target.startsWith(`${this.baseDir}${sep}`)) {
      throw new Error('KNOWLEDGE_STORAGE_PATH_INVALID');
    }
    return target;
  }

  async save(input: SaveKnowledgeFileInput): Promise<void> {
    const target = this.resolveKey(input.key);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, input.buffer, { mode: 0o600 });
  }

  async read(key: string): Promise<Buffer> {
    return readFile(this.resolveKey(key));
  }

  async remove(key: string): Promise<void> {
    await rm(this.resolveKey(key), { force: true });
  }
}

export class InMemoryKnowledgeStorage implements KnowledgeStorage {
  readonly kind = 'memory' as const;
  private readonly files = new Map<string, Buffer>();

  async save(input: SaveKnowledgeFileInput): Promise<void> {
    this.files.set(input.key, Buffer.from(input.buffer));
  }

  async read(key: string): Promise<Buffer> {
    const value = this.files.get(key);
    if (!value) throw new Error('KNOWLEDGE_STORAGE_NOT_FOUND');
    return Buffer.from(value);
  }

  async remove(key: string): Promise<void> {
    this.files.delete(key);
  }
}
